// Regenerates lib/version.ts with the current commit hash + build time. Run as a
// prebuild step (see package.json "build" / "build:cf") so Settings can show whether
// a deploy is actually live, without anyone having to remember to bump a number by hand.
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const commit = execSync("git rev-parse --short HEAD").toString().trim();
const builtAt = new Date().toISOString();

const out = fileURLToPath(new URL("../lib/version.ts", import.meta.url));
writeFileSync(
  out,
  `// Auto-generated by scripts/gen-version.mjs at build time — do not edit by hand.\n` +
    `export const APP_VERSION = "${commit}";\n` +
    `export const APP_BUILT_AT = "${builtAt}";\n`,
);
console.log(`gen-version: ${commit} @ ${builtAt}`);
