// Regenerates lib/buildInfo.ts with the current commit hash + build time. Run as a
// prebuild step (see package.json "dev" / "build" / "build:cf") so Settings can show
// whether a deploy is actually live, without anyone having to remember to check.
// (lib/version.ts holds the separate, hand-bumped human release number, e.g. "1.1".)
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const commit = execSync("git rev-parse --short HEAD").toString().trim();
const builtAt = new Date().toISOString();

const out = fileURLToPath(new URL("../lib/buildInfo.ts", import.meta.url));
writeFileSync(
  out,
  `// Auto-generated by scripts/gen-version.mjs at build time — do not edit by hand.\n` +
    `export const BUILD_COMMIT: string = "${commit}";\n` +
    `export const BUILT_AT: string = "${builtAt}";\n`,
);
console.log(`gen-version: ${commit} @ ${builtAt}`);
